version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/sahki_rails_production
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
  nginx:
    image: nginx:1.23.4
    volumes:
      - ./nginx.conf:/etc/nginx/
      - ./public:/app/public
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
